version: "3.8"

services:
  redis:
    image: "${REDIS_IMAGE}:${REDIS_TAG}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`${APP_DOMAIN}`) && PathPrefix(`/redis`)"
      - "traefik.http.routers.redis.entryPoints=web"
      - "traefik.http.middlewares.strip-redis.stripPrefix.prefixes=/redis"
      - "traefik.http.routers.redis.middlewares=strip-redis"
      - "traefik.http.services.redis.loadBalancer.server.port=${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --notify-keyspace-events
      - "Ex"
    networks:
      - web

  db:
    image: "${POSTGRES_IMAGE}:${POSTGRES_TAG}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pg.rule=Host(`${APP_DOMAIN}`) && PathPrefix(`/pg`)"
      - "traefik.http.routers.pg.entryPoints=web"
      - "traefik.http.middlewares.strip-pg.stripPrefix.prefixes=/pg"
      - "traefik.http.routers.pg.middlewares=strip-pg"
      - "traefik.http.services.pg.loadBalancer.server.port=${DB_PORT}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

  seaweedfs:
    image: "${SEAWEED_IMAGE}:${SEAWEED_TAG}"
    container_name: seaweedfs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3.rule=Host(`${APP_DOMAIN}`) && PathPrefix(`/storage`)"
      - "traefik.http.routers.s3.entryPoints=web"
      - "traefik.http.middlewares.strip-s3.stripPrefix.prefixes=/storage"
      - "traefik.http.routers.s3.middlewares=strip-s3"
      - "traefik.http.services.s3.loadBalancer.server.port=${SEAWEED_S3_PORT}"
    ports:
      - "${SEAWEED_MASTER_PORT}:${SEAWEED_MASTER_PORT}"
      - "${SEAWEED_FILER_PORT}:${SEAWEED_FILER_PORT}"
      - "${SEAWEED_S3_PORT}:${SEAWEED_S3_PORT}"
    command:
      - server
      - "-ip=0.0.0.0"
      - "-master.port=${SEAWEED_MASTER_PORT}"
      - "-filer" # <-- note the dash
      - "-filer.port=${SEAWEED_FILER_PORT}"
      - "-s3" # <-- and here
      - "-s3.port=${SEAWEED_S3_PORT}"
    volumes:
      - seaweedfs:/data
    networks:
      - web

  go_launay:
    build:
      context: "${APP_BUILD_CONTEXT}"
      dockerfile: "${APP_DOCKERFILE}"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go.rule=Host(`${APP_DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.go.entryPoints=web"
      - "traefik.http.services.go.loadBalancer.server.port=${APP_PORT}"
    environment:
      REDIS_ADDRESS: "${REDIS_ADDRESS}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      APP_PORT: "${APP_PORT}"
      SEAWEEDFS_URL: "${SEAWEEDFS_URL}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      DB_TIMEZONE: "${DB_TIMEZONE}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
      - seaweedfs
      - db
    networks:
      - web

  traefik:
    image: "${TRAEFIK_IMAGE}:${TRAEFIK_TAG}"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.dashboard.address=:${TRAEFIK_DASHBOARD_PORT}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${LE_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "${TRAEFIK_DASHBOARD_PORT}:${TRAEFIK_DASHBOARD_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - web
    depends_on:
      - go_launay
      - seaweedfs
      - db
      - redis

networks:
  web:
    external: true

volumes:
  pgdata:
  redis:
  seaweedfs:
