name: CI & Release

on:
  push:
    branches:
      - "version-*"
  pull_request:
    branches:
      - "version-*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.8"

      - name: Build backend
        working-directory: ./backend
        run: go build -v ./...

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests
        working-directory: ./frontend
        run: npm run test:ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
