name: CI & Release

on:
  push:
    branches:
      - "version-*"
  pull_request:
    branches:
      - "version-*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.8"

      - name: Build backend
        working-directory: ./backend
        run: go build -v ./...

  release:
    name: Package & Release
    needs: build
    if: startsWith(github.ref, 'refs/heads/version-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.8"

      - name: Build binary
        working-directory: ./backend
        run: go build -o go_launay .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Archive binary
        run: zip go_launay-${{ github.ref_name }}.zip go_launay

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: go_launay-${{ github.ref_name }}.zip
          asset_name: go_launay-${{ github.ref_name }}.zip
          asset_content_type: application/zip
